Repository martincostello/build-kit, pull requests merged in 2025-05, with the labels that each got.

#88 Fix Sentry workaround
  src/BuildKit/build/MartinCostello.BuildKit.targets
  src/BuildKit/build/Sentry.props
  src/BuildKit/build/Sentry.targets
Labels: bug

#91 Use SuppressDependenciesWhenPacking
  src/BuildKit/MartinCostello.BuildKit.csproj
Labels: enhancement, .NET

#77 Finalize Sentry releases
  src/BuildKit/build/Sentry.props
Labels: enhancement

#107 Do not restore npm packages for dependabot jobs
  src/BuildKit/build/Web.targets
Labels: enhancement
